### ISSUE TITLE
已经安装gcc但是还是显示缺少环境？

### ISSUE THREAD

**Issue by cwkiller** [1y0n/AV_Evasion_Tool#11]
![image](https://user-images.githubusercontent.com/19302055/97069121-72fe1f80-1600-11eb-9bbb-4d13ced1c0c3.png)

**Comment by 1y0n** [comment]
刚看到。现在还是这样吗？ 不应该出现这样的问题啊，因为检测环境的就是检测执行 gcc -version 后是否出现 tdm64 这个关键词，只要出现了，那么环境检测就是通过的

**Comment by cwkiller** [comment]
@1y0n 重启以后好了

**Comment by lzq31224** [comment]
强呀，老哥



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 我是killer <notifications@github.com&gt;
发送时间: 2020年10月26日 10:31
收件人: 1y0n/AV_Evasion_Tool <AV_Evasion_Tool@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[1y0n/AV_Evasion_Tool] 已经安装gcc但是还是显示缺少环境？ (#11)





 
@1y0n 重启以后好了
