### ISSUE TITLE
打开显示缺少必要环境

### ISSUE THREAD

**Issue by ZZtac** [1y0n/AV_Evasion_Tool#13]
gcc --version
gcc (MinGW.org GCC-8.2.0-5) 8.2.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

安装后是8.2.0
打开显示缺少必要环境，但是三个我都满足了吖？求助一下

**Comment by 1y0n** [comment]
你安装的是64位的还是32位的？  建议安装这个哦：https://github.com/jmeubank/tdm-gcc/releases/download/v9.2.0-tdm64-1/tdm64-gcc-9.2.0.exe

**Comment by ZZtac** [comment]
下载的是这个。。但是安装后就是gcc (MinGW.org GCC-8.2.0-5) 8.2.0

**Comment by 1337m4n** [comment]
下载这个https://github.com/jmeubank/tdm-gcc/releases/download/v9.2.0-tdm64-1/tdm64-gcc-9.2.0.exe
