### ISSUE TITLE
掩日3.0打开后，拖入.c以及.exe生成没有生成成功提示

### ISSUE THREAD

**Issue by 1337m4n** [1y0n/AV_Evasion_Tool#14]
![image](https://user-images.githubusercontent.com/37396317/99148761-9595cc80-26c4-11eb-82ec-9903a955350e.png)

**Comment by 1y0n** [comment]
tdm-gcc 有没有安装？

**Comment by 1337m4n** [comment]
![image](https://user-images.githubusercontent.com/37396317/99149599-0db2c100-26ca-11eb-9f6d-f214af325679.png)

**Comment by 1y0n** [comment]
tdm没问题。  把payload.c文件发我试试呢。  LyonTheNinja#gmail.com

**Comment by 1337m4n** [comment]
已发送，注意查收






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "1y0n/AV_Evasion_Tool"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月14日(星期六) 晚上10:57
收件人:&nbsp;"1y0n/AV_Evasion_Tool"<AV_Evasion_Tool@noreply.github.com&gt;;
抄送:&nbsp;"张先森"<2602210390@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [1y0n/AV_Evasion_Tool] 掩日3.0打开后，拖入.c以及.exe生成没有生成成功提示 (#14)





 
tdm没问题。  把payload.c文件发我试试呢。  LyonTheNinja#gmail.com

**Comment by 1y0n** [comment]
收到了   但是我这边是生成正常的

**Comment by 1y0n** [comment]
已经修改，下载新的release试下
