### ISSUE TITLE
gcc安装出错

### ISSUE THREAD

**Issue by yuhaoze002** [1y0n/AV_Evasion_Tool#3]
gcc安装出错了，大佬  我看那个加载安装的网站好像也不行了  http://jmeubank.github.io/tdm-gcc/，还有别的安装方法吗？gcc的

**Comment by 1y0n** [comment]
原地址：https://github.com/jmeubank/tdm-gcc/releases/download/v9.2.0-tdm64-1/tdm64-gcc-9.2.0.exe

**Comment by yuhaoze002** [comment]
多谢
