### ISSUE TITLE
大佬，膜拜，跪求更新，2.0已经过不去360了

### ISSUE THREAD

**Issue by TryA9ain** [1y0n/AV_Evasion_Tool#6]

**Comment by 1y0n** [comment]
刚测试了下，数字没问题啊

**Comment by TryA9ain** [comment]
执行1可以过，执行2现在过不了了

**Comment by 1y0n** [comment]
https://github.com/1y0n/AV_Evasion_Tool/releases/download/2.1/2.1.-.Advanced.AV.Evasion.Tool.For.Red.Team.exe

**Comment by 1y0n** [comment]
进行了小幅更新，现在试试

**Comment by 1337m4n** [comment]
360还是能过的，坐等3.0可以过Microsoft
