### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by mooneee** [1y0n/AV_Evasion_Tool#7]
生成x86没问题，生成x64就报错
![微信截图_20200907210739](https://user-images.githubusercontent.com/58715815/92390894-52603000-f14e-11ea-8682-d75e10cb8def.png)

**Comment by 1y0n** [comment]
生成时的设置截图看一下

**Comment by 1y0n** [comment]
https://github.com/1y0n/AV_Evasion_Tool/releases/download/2.1/2.1.-.Advanced.AV.Evasion.Tool.For.Red.Team.exe
试试这个呢

**Comment by mooneee** [comment]
您好，感谢回复！
不是这个，是你这个项目的另一个源码那个。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "1y0n/AV_Evasion_Tool"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月13日(星期天) 上午10:44
收件人:&nbsp;"1y0n/AV_Evasion_Tool"<AV_Evasion_Tool@noreply.github.com&gt;;
抄送:&nbsp;"illustriousDE"<276615508@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [1y0n/AV_Evasion_Tool] 报错 (#7)





 
https://github.com/1y0n/AV_Evasion_Tool/releases/download/2.1/2.1.-.Advanced.AV.Evasion.Tool.For.Red.Team.exe
 试试这个呢

**Comment by 1y0n** [comment]
这个应该是源码有问题， /optimize 和 /target:winexe 之间缺少空格😂

**Comment by mooneee** [comment]
您说的这个参数没有找到在哪个位置，是这个用x64执行有问题





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "1y0n/AV_Evasion_Tool"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月13日(星期天) 中午11:39
收件人:&nbsp;"1y0n/AV_Evasion_Tool"<AV_Evasion_Tool@noreply.github.com&gt;;
抄送:&nbsp;"illustriousDE"<276615508@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [1y0n/AV_Evasion_Tool] 报错 (#7)





 
这个应该是源码有问题， /optimize 和 /target:winexe 之间缺少空格😂

**Comment by 1y0n** [comment]
你说的应该是这个文件吧：https://github.com/1y0n/AV_Evasion_Tool/blob/d9fc0a4926413fddd756327a0759ff3edd9ea513/掩日 - 免杀执行器生成工具/Form1.cs
在代码的第188行，参数拼接的时候少了一个空格，就是这里导致了问题的产生。
![image](https://user-images.githubusercontent.com/17820255/93009767-4e516980-f5b7-11ea-9614-0b228e94092f.png)
