### ISSUE TITLE
大佬你的博客

### ISSUE THREAD

**Issue by GrapeFruitWolfs** [1y0n/AV_Evasion_Tool#8]
大佬你的博客能我进去康康不 让我瞅瞅 我觉得里面肯定有好东西 你让我看一眼就

**Comment by sinlee1** [comment]
已被加入火绒套餐：
![image](https://user-images.githubusercontent.com/29684167/101769832-874f9a80-3b22-11eb-9872-c1bec818fe07.png)

**Comment by 1y0n** [comment]
> 已被加入火绒套餐：
> ![image](https://user-images.githubusercontent.com/29684167/101769832-874f9a80-3b22-11eb-9872-c1bec818fe07.png)

好家伙，都成规则了🤣。更新筹备中......

**Comment by eggs1213** [comment]
windows defender教育版可以杀，还有360
